default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41245_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41245_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: protospace_41245_production
  username: protospace_41245
  password: <%= ENV["PROTOSPACE_41245_DATABASE_PASSWORD"] %>
